- type: job
  id: Chemist
  name: job-name-chemist
  description: job-description-chemist
  playTimeTracker: JobChemist
  setPreference: true
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 10800
  startingGear: ChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-hire # Frontier
  access:
  - Medical
  - Chemistry
  - Maintenance
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:AddComponentSpecial
    components:
    - type: SurgerySpeedModifier
      SpeedModifier: 1.75

- type: startingGear
  id: ChemistGear
  equipment:
    id: ChemistryPDA
    ears: ClothingHeadsetMedical
    belt: ChemBag
    pocket1: HandLabeler
#    eyes: ClothingEyesGlassesChemical # HL - Add departmental NF-style loadouts
    #storage:
    #back:
    #- Stuff
