  - type: job
    id: HeadOfPersonnel
    name: job-name-hop
    description: job-description-hop
    playTimeTracker: JobHeadOfPersonnel # Frontier
    requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 9000 # 2.5 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 9000 # 2.5 hours
    - !type:DepartmentTimeRequirement
      department: Science
      time: 9000 # 2.5 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 9000 # 2.5 hrs
    - !type:DepartmentTimeRequirement
      department: Command
      time: 9000 # 2.5 hours
    weight: 20
    startingGear: HoPGear
    icon: "JobIconHeadOfPersonnel"
    supervisors: job-supervisors-captain
    canBeAntag: false
    # Frontier: default access
    access:
    - Command
    - HeadOfPersonnel
    - Bar
    - Service
    - Maintenance
    - Janitor
    - Theatre
    - Kitchen
    - Chapel
    - Hydroponics
    - External
    - Cryogenics
    - Chemistry
    - Engineering
    - Research
    - Detective
    - Salvage
    - Security
    - Brig
    - Lawyer
    - Cargo
    - Atmospherics
    - Medical
    - Frontier
    accessGroups:
    - GeneralAccess
    - AllAccess
    special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]
    - !type:AddComponentSpecial
      components:
       - type: CommandStaff

  - type: startingGear
    id: HoPGear
    equipment:
#      shoes: ClothingShoesColorBrown # HL - Add NF-style departmental loadouts
      id: HoPPDA
#      gloves: ClothingHandsGlovesHop # HL - Add NF-style departmental loadouts
      ears: ClothingHeadsetAltCommand
      belt: BoxFolderClipboard
    storage:
      back:
      - Flash
