- type: job
  id: SecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: JobSecurityCadet
  startingGear: SecurityCadetGear
  icon: "JobIconSecurityCadet"
  supervisors: job-supervisors-security
  # canBeAntag: false
  ## Frontier: commented out stuff below
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  # special:
  # - !type:AddImplantSpecial
  #   implants: [ MindShieldImplant ]
  ## End Frontier: commented out stuff above
  setPreference: true
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: SecurityCadetGear
  equipment:
#    shoes: ClothingShoesBootsJackFilled # HL - Add departmental NF-style loadouts
    outerClothing: ClothingOuterArmorBasic
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: NFWeaponPistolMk58 # Frontier: use NF variant
    pocket2: BookSecurity
  storage:
    back:
    - Flash
    - Magazine9x19mmPistolFMJ
