- type: job
  id: AtmosphericTechnician
  name: job-name-atmostech
  description: job-description-atmostech
  playTimeTracker: JobAtmosphericTechnician
  setPreference: true
  requirements:
  - !type:DepartmentTimeRequirement
    department: Engineering
    time: 9000 #2.5 hrs
  startingGear: AtmosphericTechnicianGear
  icon: "JobIconAtmosphericTechnician"
  supervisors: job-supervisors-hire # Frontier
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FirefighterDay
    prototype: FireAxe

- type: startingGear
  id: AtmosphericTechnicianGear
  equipment:
#    eyes: ClothingEyesGlassesMeson # HL - Add departmental NF-style loadouts
    id: AtmosPDA
    belt: ClothingBeltUtilityEngineering # Frontier - Moved to locker
    ears: ClothingHeadsetEngineering
  #storage:
    #back:
    #- Stuff
