- type: job
  id: StationTrafficController
  name: job-name-stc
  description: job-description-stc
  playTimeTracker: JobStc
  startingGear: StcGear
  alwaysUseSpawner: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hrs
    - !type:RoleTimeRequirement
# HL start - Replace security guard requirement with security officer
#      role: JobSecurityGuard
      role: JobSecurityOfficer
      time: 10800 # 3 hrs
# HL end
  canBeAntag: false
  icon: "JobIconStc"
  supervisors: job-supervisors-sr
  weight: 160
  displayWeight: 50 # Second from the top
  setPreference: true
  access:
    - Command
    - HeadOfPersonnel
    - Bar
    - Service
    - Maintenance
    - Janitor
    - Theatre
    - Kitchen
    - Chapel
    - Hydroponics
    - External
    - Cryogenics
    - Chemistry
    - Engineering
    - Research
    - Detective
    - Salvage
    - Security
    - Brig
    - Lawyer
    - Cargo
    - Atmospherics
    - Medical
    - Frontier
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: StcGear
  equipment:
    id: StcPDA
  storage:
    back:
    - Flash
    - RubberStampStc
    - EncryptionKeyStationMaster
    - ShipVoucherFrontierStc
    - BoxFolderStc
