- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  setPreference: true
  requirements:
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 1800 #5 hrs
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 9000 #2.5 hrs
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 3600 #10 hours
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  # canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Mail # Nyanotrasen - MailCarrier, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Cargo/mail-carrier.yml
  - Quartermaster
  - Maintenance
  - Command
  - Frontier
#  - Orders # DeltaV - Orders, see Resources/Prototypes/DeltaV/Access/cargo.yml Frontier/ Removed because seems deprecated
  - External # DeltaV - for promoting salvage specialists
  - Cryogenics
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  # - !type:AddImplantSpecial
    # implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff

- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash
