- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  playTimeTracker: JobSalvageSpecialist
  setPreference: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 9000 # 2.5 hrs
  icon: "JobIconShaftMiner"
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-hire # Frontier
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
#    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist # HL - Add NF-style departmental loadouts
    id: SalvagePDA
    ears: ClothingHeadsetCargo
  #storage:
    #back:
    #- Stuff
