- type: job
  id: Bartender
  name: job-name-bartender
  description: job-description-bartender
  playTimeTracker: JobBartender
  setPreference: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 1800 #0.5 hr
  startingGear: BartenderGear
  icon: "JobIconBartender"
  supervisors: job-supervisors-hire # Frontier
  access:
  - Service
  - Maintenance
  - Bar
  extendedAccess:
  - Kitchen
  - Hydroponics
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: BartenderGear
  equipment:
#    shoes: ClothingShoesColorBlack # HL - Add NF-style departmental loadouts
    id: BartenderPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff
