- type: job
  id: Chef
  name: job-name-chef
  description: job-description-chef
  playTimeTracker: JobChef
  setPreference: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 1800 #0.5 hr
  startingGear: ChefGear
  icon: "JobIconChef"
  supervisors: job-supervisors-hire # Frontier
  access:
  - Service
  - Maintenance
  - Kitchen
  extendedAccess:
  - Hydroponics
  - Bar
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:AddComponentSpecial
    components:
    - type: ProfessionalChef #Nyano - End Summary.

- type: startingGear
  id: ChefGear
  equipment:
#    shoes: ClothingShoesColorBlack # HL - Add NF-style departmental loadouts
    id: ChefPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltChefFilled
  #storage:
    #back:
    #- Stuff
