- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  setPreference: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 9000 # 2.5 hrs
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-hire
  # canBeAntag: false
  access:
  - Service
  - Security
#  - Justice # Isn't this called Lawyer?
  - Lawyer
  - Maintenance
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: LawyerGear
  equipment:
#    shoes: ClothingShoesBootsLaceup # HL - Add NF-style departmental loadouts
    id: LawyerPDA
    ears: ClothingHeadsetSecurity
  inhand:
    - BriefcaseBrownFilled
  storage:
    back:
    - RubberStampLawyer
    - BookSpaceLaw
