- type: job
  id: Mime
  name: job-name-mime
  description: job-description-mime
  playTimeTracker: JobMime
  setPreference: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: MimeGear
  icon: "JobIconMime"
  supervisors: job-supervisors-hire # Frontier
  access:
  - Theatre
  - Maintenance
#  - Mime # Isn't this called Theatre?
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:AddComponentSpecial
    components:
    - type: MimePowers
      preventWriting: true
    - type: FrenchAccent

- type: startingGear
  id: MimeGear
  equipment:
#    gloves: ClothingHandsGlovesColorWhite # HL - Add NF-style departmental loadouts
#    shoes: ClothingShoesColorWhite # HL - Add NF-style departmental loadouts
    id: MimePDA
    pocket1: CrayonMime
    ears: ClothingHeadsetService
  storage:
    back:
    - RubberStampMime

- type: entity
  id: ActionMimeInvisibleWall
  name: Create Invisible Wall
  description: Create an invisible wall in front of you, if placeable there.
  components:
  - type: InstantAction
    priority: -1
    useDelay: 30
    icon:
      sprite: _NF/Structures/Walls/solid.rsi # Frontier
      state: full
    event: !type:InvisibleWallActionEvent
